server:
  port: ${SERVER_PORT:8082}

grpc:
  server:
    port: 9091

management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  kafka:
    bootstrap-servers: kafka:9093

    consumer:
      group-id: telemetry-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "seminars.kafka"
        spring.json.use.type.headers: false

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer